### ISSUE TITLE
Potential other options such as making avatars in the in-voice user list larger

### ISSUE THREAD

**Issue by ByzantineFailure** [ByzantineFailure/BPM-for-Discord#27]
Requested by @thejbw, maybe create some other options for modifying how discord works.  One potential option being making the list of users larger (e.g. via

``` css
.guild-channels ul .channel-voice-states li .avatar-small {
  width: 128px;
  height: 128px;
  background-size: 128px;
}

.guild-channels ul .channel-voice-states li .avatar-small {
    -webkit-transform: rotate(-90deg);
}
```
